/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Model.ModelPageVisiteurD;
import Tools.FonctionsMetier;
import javax.swing.JOptionPane;

/**
 *
 * @author simonbelhassen
 */
public class FrmPageVisiteurDefault extends javax.swing.JFrame {

    FonctionsMetier fm;
    ModelPageVisiteurD mdlVisi;
    static String indice;
    
    public FrmPageVisiteurDefault() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPVDVisiteurs = new javax.swing.JTable();
        btnPVDAjouterVis = new javax.swing.JButton();
        btnPVDModifVis = new javax.swing.JButton();
        btnPVDConfigRegs = new javax.swing.JButton();
        btnPVDNavReg = new javax.swing.JButton();
        btnPVDNavVis = new javax.swing.JButton();
        btnPVDNavStats = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDeconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblPVDVisiteurs.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tblPVDVisiteurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPVDVisiteurs);

        btnPVDAjouterVis.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        btnPVDAjouterVis.setText("Ajouter un visiteur");
        btnPVDAjouterVis.setMinimumSize(new java.awt.Dimension(100, 31));
        btnPVDAjouterVis.setPreferredSize(new java.awt.Dimension(180, 50));
        btnPVDAjouterVis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPVDAjouterVisMouseClicked(evt);
            }
        });

        btnPVDModifVis.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        btnPVDModifVis.setText("Modifier un visiteur");
        btnPVDModifVis.setMinimumSize(new java.awt.Dimension(100, 31));
        btnPVDModifVis.setPreferredSize(new java.awt.Dimension(180, 50));
        btnPVDModifVis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPVDModifVisMouseClicked(evt);
            }
        });

        btnPVDConfigRegs.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        btnPVDConfigRegs.setText("Configuration régions");
        btnPVDConfigRegs.setMinimumSize(new java.awt.Dimension(100, 31));
        btnPVDConfigRegs.setPreferredSize(new java.awt.Dimension(200, 31));
        btnPVDConfigRegs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPVDConfigRegsMouseClicked(evt);
            }
        });

        btnPVDNavReg.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnPVDNavReg.setText("Régions");
        btnPVDNavReg.setPreferredSize(new java.awt.Dimension(160, 37));
        btnPVDNavReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPVDNavRegMouseClicked(evt);
            }
        });

        btnPVDNavVis.setBackground(new java.awt.Color(255, 204, 0));
        btnPVDNavVis.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnPVDNavVis.setText("Visiteurs");
        btnPVDNavVis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        btnPVDNavVis.setPreferredSize(new java.awt.Dimension(160, 29));

        btnPVDNavStats.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnPVDNavStats.setText("Statistiques");
        btnPVDNavStats.setMaximumSize(new java.awt.Dimension(160, 37));
        btnPVDNavStats.setMinimumSize(new java.awt.Dimension(160, 37));
        btnPVDNavStats.setPreferredSize(new java.awt.Dimension(160, 37));
        btnPVDNavStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPVDNavStatsMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true)));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des Visiteurs");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
        );

        btnDeconnexion.setText("DECONNEXION");
        btnDeconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeconnexionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnPVDAjouterVis, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPVDModifVis, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnPVDConfigRegs, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnPVDNavReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btnPVDNavVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPVDNavStats, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDeconnexion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeconnexion)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPVDNavReg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPVDNavVis, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPVDNavStats, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPVDAjouterVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPVDModifVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPVDConfigRegs, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        fm = new FonctionsMetier();
        mdlVisi = new ModelPageVisiteurD();
        mdlVisi.loadDatas(fm.GetAllVisiteurs());
        tblPVDVisiteurs.setModel(mdlVisi);
        
    }//GEN-LAST:event_formWindowOpened

    private void btnPVDNavRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPVDNavRegMouseClicked
        // TODO add your handling code here:

        FrmPageRegionDefault frm = new FrmPageRegionDefault();
        frm.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnPVDNavRegMouseClicked

    private void btnPVDAjouterVisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPVDAjouterVisMouseClicked
        // TODO add your handling code here:
        
        FrmPageVisiteurAdd frm = new FrmPageVisiteurAdd();
        frm.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnPVDAjouterVisMouseClicked

    private void btnPVDModifVisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPVDModifVisMouseClicked
        // TODO add your handling code here:
        
        int column = 0;
        int row = tblPVDVisiteurs.getSelectedRow();
        
        if (row == -1) 
        {
            JOptionPane.showMessageDialog(this, "Vous devez choisir un utilisateur!!!", "INFOS", JOptionPane.INFORMATION_MESSAGE);
        }else{
            indice = tblPVDVisiteurs.getValueAt(row, column).toString();
            FrmPageVisiteurEdit frm = new FrmPageVisiteurEdit(indice);
            frm.setVisible(true);
            this.setVisible(false);
        }

        
    }//GEN-LAST:event_btnPVDModifVisMouseClicked

    private void btnPVDConfigRegsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPVDConfigRegsMouseClicked
        // TODO add your handling code here:
        
        FrmPageVisiteurRegion frm = new FrmPageVisiteurRegion();
        frm.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnPVDConfigRegsMouseClicked

    private void btnDeconnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeconnexionMouseClicked
        // TODO add your handling code here:
        
        FrmPageAccueil frm = new FrmPageAccueil();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDeconnexionMouseClicked

    private void btnPVDNavStatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPVDNavStatsMouseClicked
        // TODO add your handling code here:
        
        FrmPageStatistique frm = new FrmPageStatistique();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPVDNavStatsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPageVisiteurDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPageVisiteurDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPageVisiteurDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPageVisiteurDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPageVisiteurDefault().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeconnexion;
    private javax.swing.JButton btnPVDAjouterVis;
    private javax.swing.JButton btnPVDConfigRegs;
    private javax.swing.JButton btnPVDModifVis;
    private javax.swing.JButton btnPVDNavReg;
    private javax.swing.JButton btnPVDNavStats;
    private javax.swing.JButton btnPVDNavVis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPVDVisiteurs;
    // End of variables declaration//GEN-END:variables
}
